format_version: "11"
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: other
meta:
  bitrise.io:
    machine_type_id: g2-m1.4core
    stack: osx-xcode-14.3.x-ventura
app:
  envs:
  - BITRISE_PROJECT_PATH: ./old-ios-test/old-ios-test.xcodeproj
  - BITRISE_SCHEME: old-ios-testUITests
pipelines:
  run-tests:
    stages:
    - test: {}
stages:
  test:
    workflows:
    - test-ios-13-sim: {}
    - test-ios-14-sim: {}
workflows:
  _setup:
    steps:
    - activate-ssh-key: {}
    - git-clone: {}
  _ui-test-sim:
    before_run:
    - _setup
    steps:
    - xcode-build-for-test@1: {}
    - xcode-test@4:
        inputs:
        - destination: $TEST_DEVICE
        - collect_simulator_diagnostics: always
        - log_formatter: xcodebuild
    - deploy-to-bitrise-io@2: {}
  test-ios-13-sim:
    envs:
    - TEST_DEVICE: platform=iOS Simulator,name=iPhone 11,OS=13.7
    after_run:
    - _ui-test-sim
  test-ios-14-sim:
    envs:
    - TEST_DEVICE: platform=iOS Simulator,name=iPhone 14,OS=latest
    after_run:
    - _ui-test-sim